# See https://github.com/lycheeverse/lychee/blob/master/lychee.example.toml
#############################  Display  #############################

# Verbose program output
verbose = "info"

#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs.
cache = true

# Discard all cached requests older than this duration.
max_cache_age = "1d"

#############################  Runtime  #############################

# Maximum number of allowed redirects.
max_redirects = 50

# Maximum number of allowed retries before a link is declared dead.
max_retries = 3

#############################  Requests  ############################

# User agent to send with each request.
user_agent = "Mozilla/5.0"

# Website timeout from connect to response finished.
timeout = 20

# Minimum wait time in seconds between retries of failed requests.
retry_wait_time = 2

#############################  Requests  ############################

# Comma-separated list of accepted status codes for valid links.
accept = [200, 429, 403]

# Proceed for server connections considered insecure (invalid TLS).
insecure = false

# When links are available using HTTPS, treat HTTP links as errors.
require_https = true

#############################  Exclusions  ##########################

# Check links inside `<code>` and `<pre>` blocks as well as Markdown code
# blocks.
include_verbatim = true

# Ignore case of paths when matching glob patterns.
glob_ignore_case = false

# Exclude URLs from checking (supports regex).
exclude = [
  "https://www.gnu.org/software/emacs",
  "https://www.gnu.org/software/make",
  "https://www.gnu.org/software/binutils",
  "https://makeapullrequest.com",
  "https://x.com/0xAX"
]

# Exclude these filesystem paths from getting checked.
exclude_path = ["vendor"]

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true.
exclude_all_private = true
